package com.example.acer.gunungtertinggidiindonesia;

import java.util.ArrayList;

public class MountainData {
    public static String[][] data = new String[][]{
            {"Puncak Jaya", "Puncak Jaya atau Carstensz Pyramid ialah sebuah puncak yang menjadi bagian dari Barisan Sudirman yang terdapat di Provinsi Papua, Indonesia. Puncak Jaya mempunyai ketinggian 4.884 m dan di sekitarnya terdapat gletser Carstensz, satu-satunya gletser tropika di Indonesia, yang kemungkinan besar segera akan lenyap akibat pemanasan global. Puncak ini merupakan gunung yang tertinggi di Indonesia kawasan Oceania. Puncak Jaya adalah salah satu dari tujuh puncak dunia.", "https://upload.wikimedia.org/wikipedia/commons/3/3f/Puncakjaya.jpg", "4.884 m (16.024 ft)", "Papua", "Tidak aktif", "6Q7VW58P+5J", "Puncak Jaya, Indonesia" },
            {"Gunung Kerinci", "Gunung Kerinci (juga dieja \"Kerintji\", dan dikenal sebagai Gunung Gedang, Berapi Kurinci, Kerinchi, Korinci, atau Puncak Indrapura) adalah gunung tertinggi di Sumatra, gunung berapi tertinggi di Indonesia, dan puncak tertinggi di Indonesia di luar Papua. Gunung Kerinci terletak di Provinsi Jambi, di Pegunungan Bukit Barisan, dekat pantai barat, dan terletak sekitar 130 km sebelah selatan Padang Provinsi Sumatra Barat. Gunung ini dikelilingi hutan lebat Taman Nasional Kerinci Seblat dan merupakan habitat harimau sumatra dan badak sumatra.", "https://upload.wikimedia.org/wikipedia/commons/f/f4/Uprising-mount_kerinci.jpg", "3.805 m (12.480 ft)", "Jambi", "Aktif", "8737+8M Liki, South Lubuk Gadang, South Solok Regency, West Sumatra", "Gunung Kerinci, Indonesia"},
            {"Gunung Rinjani", "Gunung Rinjani adalah gunung yang berlokasi di Pulau Lombok, Nusa Tenggara Barat. Gunung yang merupakan gunung berapi kedua tertinggi di Indonesia dengan ketinggian 3.726 m dpl serta terletak pada lintang 8º25' LS dan 116º28' BT ini merupakan gunung favorit bagi pendaki Indonesia karena keindahan pemandangannya. Gunung ini merupakan bagian dari Taman Nasional Gunung Rinjani yang memiliki luas sekitar 41.330 ha dan ini akan diusulkan penambahannya sehingga menjadi 76.000 ha ke arah barat dan timur. ", "https://www.pagitrans.com/wp-content/uploads/2019/03/Agen-Sewa-Mobil-Lombok-dan-Paket-Wisata-Gunung-Rinjani_nyero.id_.jpg", "3.726 m (12.224 ft)", "Lombok", "Aktif", "HFQ4+FW Sembaloenboemboeng, Sembalun Bumbung, East Lombok Regency, West Nusa Tenggara", "Gunung Rinjani, Indonesia" },
            {"Gunung Semeru", "Gunung Semeru atau Gunung Meru adalah sebuah gunung berapi kerucut di Jawa Timur, Indonesia. Gunung Semeru merupakan gunung tertinggi di Pulau Jawa, dengan puncaknya Mahameru, 3.676 meter dari permukaan laut (mdpl). Gunung Semeru juga merupakan gunung berapi tertinggi ketiga di Indonesia setelah Gunung Kerinci di Sumatra dan Gunung Rinjani di Nusa Tenggara Barat. Kawah di puncak Gunung Semeru dikenal dengan nama Jonggring Saloko. Gunung Semeru secara administratif termasuk dalam wilayah dua kabupaten, yakni Kabupaten Malang dan Kabupaten Lumajang, Provinsi Jawa Timur. Gunung ini termasuk dalam kawasan Taman Nasional Bromo Tengger Semeru.", "https://cdn-image.bisnis.com/posts/2019/08/12/1135593/semeru21.jpg", "3.676 m (12.060 ft)", "Jawa Timur", "Aktif", "VWRC+WX Gunungsriti, Kalibening, Pronojiwo, Lumajang Regency, East Java","Gunung Semeru, Indonesia"},
            {"Gunung Sanggar", "Berada di komplek pegunungan yang sama dengan Gunung Rinjani, Gunung Sanggar memiliki ketinggian 3.564 mdpl. Meski merupakan salah satu gunung tertinggi di Indonesia, namun Gunung Sanggar ini tidaklah seterkenal Rinjani.", "https://cdn-image.hipwee.com/wp-content/uploads/2015/05/sanggar-kejaam29.blogspot.jpg", "3.564 m (11.693 ft)", "Lombok", "Aktif", "HFJ5+CC Sembaloenboemboeng, Sembalun Bumbung, East Lombok Regency, West Nusa Tenggara", "Gunung Sanggar, Indonesia"},
            {"Gunung Latimojong", "Gunung Latimojong adalah satu nama gunung di Kabupaten Enrekang, Sulawesi Selatan, Indonesia. Gunung Latimojong berada di tengah-tengah Sulawesi Selatan. Sebagian besar pengunungan ini terletak di daerah Kabupaten Enrekang. Gunung Latimojong merupakan gunung yang tertinggi di Sulawesi Selatan dengan ketinggian 3.478 meter, puncaknya yang bernama Bulu Rante Mario.", "https://upload.wikimedia.org/wikipedia/id/thumb/7/71/Puncak-rantemario.jpg/420px-Puncak-rantemario.jpg", "3.478 m (11.410 ft)", "Sulawesi Selatan", "Tidak aktif", "H33F+QH Tibusan, Buntu Sarek, Luwu Regency, South Sulawesi", "Gunung Latimojong, Indonesia"},
            {"Gunung Slamet", "Gunung Slamet (3.428 meter dpl.) adalah sebuah gunung berapi kerucut yang terdapat di Pulau Jawa, Indonesia. Gunung Slamet terletak di antara 5 kabupaten, yaitu Kabupaten Brebes, Kabupaten Banyumas, Kabupaten Purbalingga, Kabupaten Tegal, dan Kabupaten Pemalang, Provinsi Jawa Tengah. Gunung Slamet merupakan gunung tertinggi di Jawa Tengah serta kedua tertinggi di Pulau Jawa setelah Gunung Semeru. Kawah IV merupakan kawah terakhir yang masih aktif sampai sekarang, dan terakhir aktif hingga pada level siaga medio-2009. ", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Gunung_Slamet_dari_Kr_Salam.jpg/420px-Gunung_Slamet_dari_Kr_Salam.jpg", "3.428 m (11.247 ft)","Jawa Tengah", "Aktif", "Q66C+82 Baturaden, Dusun III Kalipagu, Ketenger, Banyumas, Central Java", "Gunung Slamet, Indonesia"},
            {"Gunung Sumbing", "Gunung Sumbing adalah gunung api yang terdapat di Jawa Tengah, Indonesia. (Ketinggian puncak 3.371 mdpl), gunung Sumbing merupakan gunung tertinggi ketiga di Pulau Jawa setelah Gunung Semeru dan Gunung Slamet. Gunung ini secara administratif terletak di tiga wilayah kabupaten, yaitu Kabupaten Magelang; Kabupaten Temanggung; dan Kabupaten Wonosobo. Bersama dengan Gunung Sindoro, Gunung Sumbing membentuk bentang alam gunung kembar, seperti Gunung Merapi dan Gunung Merbabu, apabila dilihat dari arah Temanggung. Celah antara gunung ini dan Gunung Sindoro dilalui oleh jalan provinsi yang menghubungkan kota Temanggung dan kota Wonosobo. Jalan ini biasa dijuluki sebagai \"Kledung Pass\".", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Sumbing%2C_Java.jpg/420px-Sumbing%2C_Java.jpg", "3.371 m (11.060 ft)", "Jawa Tengah", "Aktif", "J37C+XX Windusari, Magelang, Central Java", "Gunung Sumbing, Indonesia"},
            {"Gunung Raung", "Gunung Raung (puncak tertinggi: 3.260 m dpl) adalah gunung berapi kerucut yang terletak di ujung timur Pulau Jawa, Indonesia. Secara administratif, kawasan gunung ini termasuk dalam wilayah tiga kabupaten di wilayah Besuki, Jawa Timur, yaitu Banyuwangi, Bondowoso, dan Jember. Secara geografis, lokasi gunung ini berada dalam kawasan kompleks Pegunungan Ijen dan menjadi puncak tertinggi dari gugusan pegunungan tersebut.", "https://inspirasijatim.com/wp-content/uploads/2018/04/Gunung-Raung.jpg", "3.260 m (10.700 ft)", "Jawa Timur", "Aktif", "V2FW+M8 Djampi, Mlaten, Jampit, Bondowoso Regency, East Java", "Gunung Raung, Indonesia"},
            {"Gunung Ceremai", "Gunung Ceremai (seringkali secara salah kaprah dinamakan \"Ciremai\") adalah gunung berapi kerucut yang secara administratif termasuk dalam wilayah dua kabupaten, yakni Kabupaten Kuningan dan Kabupaten Majalengka, Provinsi Jawa Barat. Posisi geografis puncaknya terletak pada 6° 53' 30\" LS dan 108° 24' 00\" BT, dengan ketinggian 3.078 m di atas permukaan laut. Gunung ini merupakan gunung tertinggi di Jawa Barat. Gunung ini memiliki kawah ganda. Kawah barat yang beradius 400 m terpotong oleh kawah timur yang beradius 600 m. Pada ketinggian sekitar 2.900 m dpl di lereng selatan terdapat bekas titik letusan yang dinamakan Gowa Walet. ", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Ciremai.jpg/420px-Ciremai.jpg", "3.078 m (10.098 ft)", "Jawa Barat", "Aktif", "4C44+MM Cigugur, Kuningan Regency, West Java", "Gunung Ceremai, Indonesia"}
    };
    public static ArrayList<Mountain> getListData(){
        ArrayList<Mountain> list = new ArrayList<>();
        for (String[] aData : data){
            Mountain mountain = new Mountain();
            mountain.setName(aData[0]);
            mountain.setDesc(aData[1]);
            mountain.setPhoto(aData[2]);
            mountain.setTinggi(aData[3]);
            mountain.setLokasi(aData[4]);
            mountain.setKondisi(aData[5]);
            mountain.setGmaps(aData[6]);
            mountain.setGimage(aData[7]);
            list.add(mountain);
        }
        return list;
    }
}
